image: node:16

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - npm install

test:
  stage: test
  needs: [setup]
  script:
    - npm run lint
    - npm test -- --coverage
